# Generated by Django 2.2.3 on 2019-08-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
            ],
        ),
    ]
